name: CI

on:
  pull_request:

env:
  node_version: '14.x'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci --prefer-offline
      - run: npm run test:ci

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - run: npm ci --prefer-offline
      - run: npm run lint